### PR TITLE
add idea for generic type inference

### PR DESCRIPTION
**Pull request by mfelsche**

### CODE REVIEW

**Comment by Theodus** [comment]
I would be interested in working on this during the Google Summer of Code this year. Would it also make sense to add [finite recursive type aliases](https://github.com/ponylang/ponyc/issues/267)?

**Comment by mfelsche** [comment]
Yes, i think it makes a lot of sense. I just didnt get to add it yet. @Theodus i am gonna add you as mentor here.

**Comment by Theodus** [comment]
@mfelsche I intend to participate as a student, so I wouldn't be eligible for being a mentor as well.

**Comment by mfelsche** [comment]
Got it, gonna remove you. Hope i can be a good enough mentor. If anyone else wants to jump in, you are welcome.

**Pull request merged**
